language: php
php:
  - 7.4

before_script:
  - composer install --no-interaction --prefer-source --dev

jobs:
  include:
    - name: phpunit
      script: composer run phpunit
    - name: phpcs
      script: composer run check-style
